#!/bin/bash
# Create symlinks from the home directory to dotfiles in ~/dotfiles.


dir=~/dotfiles  # dotfiles directory
mkdir ~/dotfiles_old

cd $dir
files=`ls`

# Move any existing dotfiles in homedir to dotfiles_old directory,
# then create symlinks.
for file in $files; do
    mv ~/.$file ~/dotfiles_old/
    ln -s $dir/$file ~/.$file
done

echo "done!"
