#!/bin/bash
# Create symlinks from the home directory to dotfiles in ~/dotfiles.


dir=~/dotfiles  # dotfiles directory
mkdir ~/dotfiles_old

echo "Changing to the $dir directory"
cd $dir
files=`ls`

# Move any existing dotfiles in homedir to dotfiles_old directory,
# then create symlinks.
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done
